aws_region = "desired region"
vpc_cidr_block = "desired cidr block"
public_subnet_cidr_block = "desired cidr block"
private_subnet_cidr_block = "desired cidr block"
key_pair_name = "your key"
ami_id = "ami-12345678"
instance_type = "your instance type"
public_instance_count = desired number of instances
private_instance_count = desired number of instances
